/* eslint-disable camelcase */
const input = {
  href: 'http://localhost:3000/api/service_dialogs/57',
  id: '57',
  description: 'Description of testing Dialog',
  buttons: 'submit,cancel',
  created_at: '2018-10-23T14:26:50Z',
  updated_at: '2018-10-23T14:26:50Z',
  label: 'Testing dialog',
  content: [
    {
      href: 'http://localhost:3000/api/service_dialogs/57',
      id: '57',
      description: 'Description of testing Dialog',
      buttons: 'submit,cancel',
      created_at: '2018-10-23T14:26:50Z',
      updated_at: '2018-10-23T14:26:50Z',
      label: 'Testing dialog',
      dialog_tabs: [
        {
          href: 'http://localhost:3000/api/service_dialogs/553',
          id: '553',
          description: 'Text boxes and text areas',
          display: null,
          created_at: '2018-10-23T14:26:49Z',
          updated_at: '2018-10-23T14:26:50Z',
          label: 'Tab 1',
          display_method: null,
          display_method_options: null,
          dialog_id: '57',
          position: 0,
          dialog_groups: [
            {
              href: 'http://localhost:3000/api/service_dialogs/637',
              id: '637',
              description: null,
              display: null,
              created_at: '2018-10-23T14:26:49Z',
              updated_at: '2018-10-23T14:29:03Z',
              label: 'Text boxes',
              display_method: null,
              display_method_options: null,
              dialog_tab_id: '553',
              position: 0,
              dialog_fields: [
                {
                  href: 'http://localhost:3000/api/service_dialogs/4327',
                  id: '4327',
                  name: 'text_box_1',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Box',
                  dialog_group_id: '637',
                  position: 0,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4328',
                  id: '4328',
                  name: 'text_box_2',
                  description: 'Helper text',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Box with help',
                  dialog_group_id: '637',
                  position: 1,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4329',
                  id: '4329',
                  name: 'text_box_3',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: true,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Box required',
                  dialog_group_id: '637',
                  position: 2,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4330',
                  id: '4330',
                  name: 'text_box_4',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Box readonly',
                  dialog_group_id: '637',
                  position: 3,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: true,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4331',
                  id: '4331',
                  name: 'text_box_5',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '"hello"',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Box default',
                  dialog_group_id: '637',
                  position: 4,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4332',
                  id: '4332',
                  name: 'text_box_6',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Box unvisible',
                  dialog_group_id: '637',
                  position: 5,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: false,
                  type: 'DialogFieldTextBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4333',
                  id: '4333',
                  name: 'text_box_7',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Box with validator',
                  dialog_group_id: '637',
                  position: 6,
                  validator_type: null,
                  validator_rule: '[0-9]',
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4334',
                  id: '4334',
                  name: 'text_box_8',
                  description: '',
                  data_type: 'integer',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Box integer value',
                  dialog_group_id: '637',
                  position: 7,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4335',
                  id: '4335',
                  name: 'text_box_9',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Box string value',
                  dialog_group_id: '637',
                  position: 8,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
              ],
            },
            {
              href: 'http://localhost:3000/api/service_dialogs/638',
              id: '638',
              description: '',
              display: 'edit',
              created_at: '2018-10-23T14:26:49Z',
              updated_at: '2018-10-23T14:29:03Z',
              label: 'Text areas',
              display_method: null,
              display_method_options: null,
              dialog_tab_id: '553',
              position: 1,
              dialog_fields: [
                {
                  href: 'http://localhost:3000/api/service_dialogs/4336',
                  id: '4336',
                  name: 'textarea_box_1',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Area',
                  dialog_group_id: '638',
                  position: 0,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextAreaBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
              ],
            },
          ],
        },
        {
          href: 'http://localhost:3000/api/service_dialogs/554',
          id: '554',
          description: 'Checks',
          display: 'edit',
          created_at: '2018-10-23T14:26:49Z',
          updated_at: '2018-10-23T14:26:50Z',
          label: 'Tab 2',
          display_method: null,
          display_method_options: null,
          dialog_id: '57',
          position: 1,
          dialog_groups: [
            {
              href: 'http://localhost:3000/api/service_dialogs/639',
              id: '639',
              description: '',
              display: 'edit',
              created_at: '2018-10-23T14:26:49Z',
              updated_at: '2018-10-23T14:29:03Z',
              label: 'Check boxes',
              display_method: null,
              display_method_options: null,
              dialog_tab_id: '554',
              position: 0,
              dialog_fields: [
                {
                  href: 'http://localhost:3000/api/service_dialogs/4337',
                  id: '4337',
                  name: 'check_box_1',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Check Box',
                  dialog_group_id: '639',
                  position: 0,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldCheckBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4338',
                  id: '4338',
                  name: 'check_box_2',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: 't',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Check Box checked',
                  dialog_group_id: '639',
                  position: 1,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldCheckBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
              ],
            },
            {
              href: 'http://localhost:3000/api/service_dialogs/640',
              id: '640',
              description: 'Description',
              display: 'edit',
              created_at: '2018-10-23T14:26:49Z',
              updated_at: '2018-10-23T14:29:03Z',
              label: 'Radios',
              display_method: null,
              display_method_options: null,
              dialog_tab_id: '554',
              position: 1,
              dialog_fields: [
                {
                  href: 'http://localhost:3000/api/service_dialogs/4339',
                  id: '4339',
                  name: 'radio_button_1',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: [
                    [
                      '1',
                      'One',
                    ],
                    [
                      '2',
                      'Two',
                    ],
                    [
                      '3',
                      'Three',
                    ],
                  ],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    sort_by: 'description',
                    sort_order: 'ascending',
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Radio Button',
                  dialog_group_id: '640',
                  position: 0,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldRadioButton',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4340',
                  id: '4340',
                  name: 'radio_button_2',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: [
                    [
                      '1',
                      'One',
                    ],
                    [
                      '2',
                      'Two',
                    ],
                    [
                      '3',
                      'Three',
                    ],
                  ],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    sort_by: 'value',
                    sort_order: 'ascending',
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Radio Button sorted by',
                  dialog_group_id: '640',
                  position: 1,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldRadioButton',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4341',
                  id: '4341',
                  name: 'radio_button_4',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '2',
                  values: [
                    [
                      '1',
                      'One',
                    ],
                    [
                      '2',
                      'Two',
                    ],
                    [
                      '3',
                      'Three',
                    ],
                  ],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    sort_by: 'description',
                    sort_order: 'ascending',
                  },
                  created_at: '2018-10-23T14:29:03Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Radio Button default',
                  dialog_group_id: '640',
                  position: 2,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldRadioButton',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
              ],
            },
          ],
        },
        {
          href: 'http://localhost:3000/api/service_dialogs/555',
          id: '555',
          description: '',
          display: 'edit',
          created_at: '2018-10-23T14:26:49Z',
          updated_at: '2018-10-23T14:26:50Z',
          label: 'Tab 3',
          display_method: null,
          display_method_options: null,
          dialog_id: '57',
          position: 2,
          dialog_groups: [
            {
              href: 'http://localhost:3000/api/service_dialogs/641',
              id: '641',
              description: 'Description',
              display: 'edit',
              created_at: '2018-10-23T14:26:49Z',
              updated_at: '2018-10-23T14:29:03Z',
              label: 'Dropdowns',
              display_method: null,
              display_method_options: null,
              dialog_tab_id: '555',
              position: 0,
              dialog_fields: [
                {
                  href: 'http://localhost:3000/api/service_dialogs/4342',
                  id: '4342',
                  name: 'dropdown_list_1',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: [
                    [
                      null,
                      '<None>',
                    ],
                    [
                      '1',
                      'One',
                    ],
                    [
                      '3',
                      'Three',
                    ],
                    [
                      '2',
                      'Two',
                    ],
                  ],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    sort_by: 'description',
                    sort_order: 'ascending',
                    force_multi_value: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Dropdown',
                  dialog_group_id: '641',
                  position: 0,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldDropDownList',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4343',
                  id: '4343',
                  name: 'dropdown_list_2',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '2',
                  values: [
                    [
                      null,
                      '<None>',
                    ],
                    [
                      '1',
                      'One',
                    ],
                    [
                      '3',
                      'Three',
                    ],
                    [
                      '2',
                      'Two',
                    ],
                  ],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    sort_by: 'description',
                    sort_order: 'ascending',
                    force_multi_value: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Dropdown default value',
                  dialog_group_id: '641',
                  position: 1,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldDropDownList',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4344',
                  id: '4344',
                  name: 'dropdown_list_3',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: [
                    [
                      null,
                      '<None>',
                    ],
                    [
                      '1',
                      'One',
                    ],
                    [
                      '3',
                      'Three',
                    ],
                    [
                      '2',
                      'Two',
                    ],
                  ],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    sort_by: 'description',
                    sort_order: 'ascending',
                    force_multi_value: true,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Dropdown multiselect',
                  dialog_group_id: '641',
                  position: 2,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldDropDownList',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4345',
                  id: '4345',
                  name: 'dropdown_list_4',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: [
                    [
                      null,
                      '<None>',
                    ],
                    [
                      '1',
                      'One',
                    ],
                    [
                      '2',
                      'Two',
                    ],
                    [
                      '3',
                      'Three',
                    ],
                  ],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    sort_by: 'value',
                    sort_order: 'ascending',
                    force_multi_value: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Dropdown sort by value',
                  dialog_group_id: '641',
                  position: 3,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldDropDownList',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
              ],
            },
          ],
        },
        {
          href: 'http://localhost:3000/api/service_dialogs/556',
          id: '556',
          description: '',
          display: 'edit',
          created_at: '2018-10-23T14:26:50Z',
          updated_at: '2018-10-23T14:26:50Z',
          label: 'Tab 4',
          display_method: null,
          display_method_options: null,
          dialog_id: '57',
          position: 3,
          dialog_groups: [
            {
              href: 'http://localhost:3000/api/service_dialogs/642',
              id: '642',
              description: 'Description',
              display: 'edit',
              created_at: '2018-10-23T14:26:49Z',
              updated_at: '2018-10-23T14:29:03Z',
              label: 'Datepickers',
              display_method: null,
              display_method_options: null,
              dialog_tab_id: '556',
              position: 0,
              dialog_fields: [
                {
                  href: 'http://localhost:3000/api/service_dialogs/4346',
                  id: '4346',
                  name: 'date_control_1',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    show_past_dates: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Datepicker',
                  dialog_group_id: '642',
                  position: 0,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldDateControl',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4347',
                  id: '4347',
                  name: 'date_control_2',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    show_past_dates: true,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Datepicker with past days',
                  dialog_group_id: '642',
                  position: 1,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldDateControl',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
              ],
            },
            {
              href: 'http://localhost:3000/api/service_dialogs/643',
              id: '643',
              description: 'Description',
              display: 'edit',
              created_at: '2018-10-23T14:26:50Z',
              updated_at: '2018-10-23T14:29:03Z',
              label: 'Timepickers',
              display_method: null,
              display_method_options: null,
              dialog_tab_id: '556',
              position: 1,
              dialog_fields: [
                {
                  href: 'http://localhost:3000/api/service_dialogs/4348',
                  id: '4348',
                  name: 'date_time_control_1',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    show_past_dates: false,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Timepicker',
                  dialog_group_id: '643',
                  position: 0,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldDateTimeControl',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4349',
                  id: '4349',
                  name: 'date_time_control_2',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    show_past_dates: true,
                  },
                  created_at: '2018-10-23T14:26:49Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Timepicker with past days',
                  dialog_group_id: '643',
                  position: 1,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldDateTimeControl',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
              ],
            },
          ],
        },
        {
          href: 'http://localhost:3000/api/service_dialogs/557',
          id: '557',
          description: 'New tab 4',
          display: 'edit',
          created_at: '2018-10-23T14:26:50Z',
          updated_at: '2018-10-23T14:26:50Z',
          label: 'Tab 5',
          display_method: null,
          display_method_options: null,
          dialog_id: '57',
          position: 4,
          dialog_groups: [
            {
              href: 'http://localhost:3000/api/service_dialogs/644',
              id: '644',
              description: 'Description',
              display: 'edit',
              created_at: '2018-10-23T14:26:50Z',
              updated_at: '2018-10-23T14:29:03Z',
              label: 'Tag control',
              display_method: null,
              display_method_options: null,
              dialog_tab_id: '557',
              position: 0,
              dialog_fields: [
                {
                  href: 'http://localhost:3000/api/service_dialogs/4350',
                  id: '4350',
                  name: 'tag_control_1',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: [],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    category_id: null,
                    force_single_value: false,
                    sort_by: 'description',
                    sort_order: 'ascending',
                  },
                  created_at: '2018-10-23T14:26:50Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Tag Control',
                  dialog_group_id: '644',
                  position: 0,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTagControl',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4351',
                  id: '4351',
                  name: 'tag_control_2',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: [],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    category_id: null,
                    force_single_value: true,
                    sort_by: 'description',
                    sort_order: 'ascending',
                  },
                  created_at: '2018-10-23T14:26:50Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Tag Control single value',
                  dialog_group_id: '644',
                  position: 1,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTagControl',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4352',
                  id: '4352',
                  name: 'tag_control_3',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: [
                    {
                      id: null,
                      name: '<None>',
                      description: '<None>',
                    },
                    {
                      id: 36,
                      name: 'gold',
                      description: 'Gold',
                    },
                    {
                      id: 37,
                      name: 'platinum',
                      description: 'Platinum',
                    },
                    {
                      id: 35,
                      name: 'silver',
                      description: 'Silver',
                    },
                  ],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    category_id: '34',
                    force_single_value: true,
                    sort_by: 'description',
                    sort_order: 'ascending',
                    category_description: 'Service Level',
                    category_name: 'service_level',
                    category_single_value: true,
                  },
                  created_at: '2018-10-23T14:26:50Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Tag Control category',
                  dialog_group_id: '644',
                  position: 2,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTagControl',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
              ],
            },
          ],
        },
        {
          href: 'http://localhost:3000/api/service_dialogs/558',
          id: '558',
          description: '',
          display: 'edit',
          created_at: '2018-10-23T14:26:50Z',
          updated_at: '2018-10-23T14:26:50Z',
          label: 'Mixed',
          display_method: null,
          display_method_options: null,
          dialog_id: '57',
          position: 5,
          dialog_groups: [
            {
              href: 'http://localhost:3000/api/service_dialogs/645',
              id: '645',
              description: 'Description',
              display: 'edit',
              created_at: '2018-10-23T14:26:50Z',
              updated_at: '2018-10-23T14:29:03Z',
              label: 'New Section',
              display_method: null,
              display_method_options: null,
              dialog_tab_id: '558',
              position: 0,
              dialog_fields: [
                {
                  href: 'http://localhost:3000/api/service_dialogs/4353',
                  id: '4353',
                  name: 'text_box_10',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:50Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Box',
                  dialog_group_id: '645',
                  position: 0,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4354',
                  id: '4354',
                  name: 'textarea_box_2',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:50Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Text Area',
                  dialog_group_id: '645',
                  position: 1,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldTextAreaBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4355',
                  id: '4355',
                  name: 'check_box_3',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:50Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Check Box',
                  dialog_group_id: '645',
                  position: 2,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldCheckBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4356',
                  id: '4356',
                  name: 'check_box_4',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    protected: false,
                  },
                  created_at: '2018-10-23T14:26:50Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Check Box',
                  dialog_group_id: '645',
                  position: 3,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldCheckBox',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4357',
                  id: '4357',
                  name: 'dropdown_list_5',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: [
                    [
                      null,
                      '<None>',
                    ],
                    [
                      '1',
                      'One',
                    ],
                    [
                      '3',
                      'Three',
                    ],
                    [
                      '2',
                      'Two',
                    ],
                  ],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    sort_by: 'description',
                    sort_order: 'ascending',
                    force_multi_value: false,
                  },
                  created_at: '2018-10-23T14:26:50Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Dropdown',
                  dialog_group_id: '645',
                  position: 4,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldDropDownList',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4358',
                  id: '4358',
                  name: 'radio_button_3',
                  description: '',
                  data_type: 'string',
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: [
                    [
                      '1',
                      'One',
                    ],
                    [
                      '2',
                      'Two',
                    ],
                    [
                      '3',
                      'Three',
                    ],
                  ],
                  values_method: null,
                  values_method_options: {},
                  options: {
                    sort_by: 'description',
                    sort_order: 'ascending',
                  },
                  created_at: '2018-10-23T14:26:50Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Radio Button',
                  dialog_group_id: '645',
                  position: 5,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldRadioButton',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/4359',
                  id: '4359',
                  name: 'date_time_control_3',
                  description: '',
                  data_type: null,
                  notes: null,
                  notes_display: null,
                  display: 'edit',
                  display_method: null,
                  display_method_options: {},
                  required: false,
                  required_method: null,
                  required_method_options: {},
                  default_value: '',
                  values: null,
                  values_method: null,
                  values_method_options: {},
                  options: {
                    show_past_dates: false,
                  },
                  created_at: '2018-10-23T14:26:50Z',
                  updated_at: '2018-10-23T14:29:03Z',
                  label: 'Timepicker',
                  dialog_group_id: '645',
                  position: 6,
                  validator_type: null,
                  validator_rule: null,
                  reconfigurable: false,
                  dynamic: false,
                  show_refresh_button: false,
                  load_values_on_init: false,
                  read_only: false,
                  auto_refresh: false,
                  trigger_auto_refresh: false,
                  visible: true,
                  type: 'DialogFieldDateTimeControl',
                  resource_action: {
                    action: null,
                    resource_type: 'DialogField',
                    ae_namespace: null,
                    ae_class: null,
                    ae_instance: null,
                    ae_message: null,
                    ae_attributes: {},
                  },
                  dialog_field_responders: [],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  actions: [
    {
      name: 'refresh_dialog_fields',
      method: 'post',
      href: 'http://localhost:3000/api/service_dialogs/57',
    },
    {
      name: 'delete',
      method: 'post',
      href: 'http://localhost:3000/api/service_dialogs/57',
    },
    {
      name: 'edit',
      method: 'post',
      href: 'http://localhost:3000/api/service_dialogs/57',
    },
    {
      name: 'copy',
      method: 'post',
      href: 'http://localhost:3000/api/service_dialogs/57',
    },
    {
      name: 'delete',
      method: 'delete',
      href: 'http://localhost:3000/api/service_dialogs/57',
    },
  ],
};

export default input;
