const customStyles = {
  indicatorSeparator: () => ({
    display: 'none',
  }),
  indicatorsContainer: provided => ({
    ...provided,
    lineHeight: 0,
  }),
  input: provided => ({
    ...provided,
    marginLeft: 0,
    marginTop: 0,
    marginBottom: 0,
    paddingBottom: 0,
    paddingTop: 0,
    fontWeight: '600',
    color: 'rgb(54, 54, 54)',
  }),
  placeholder: (provided, { isDisabled }) => ({
    ...provided,
    padding: '0 6px',
    color: isDisabled ? 'rgba(77, 82, 88, 0.4)' : '#999999',
    fontWeight: '600',
    paddingLeft: 0,
    marginLeft: 0,

  }),
  option: (provided, { isFocused, isSelected, isMulti }) => ({
    ...provided,
    'background-color': isSelected ? '#0088ce' : isFocused ? '#def3ff' : '#ffffff',
    'border-color': isSelected ? '#0088ce' : isFocused ? '#bee1f4' : 'transparent',
    'border-style': 'solid',
    'border-width': '1px 0',
    color: isSelected ? '#fff' : isFocused ? '#4d5258' : provided.color,
    padding: '1px 10px',
    fontWeight: '400',
    cursor: 'pointer',
    '&::after': {
      fontFamily: 'FontAwesome',
      color: isMulti && isSelected ? 'white' : null,
      content: isMulti && isSelected ? '" \\f00c "' : null,
      float: isMulti ? 'right' : 'initial',
    },
  }),
  dropdownIndicator: (provided, { isDisabled }) => ({
    ...provided,
    color: 'rgb(77, 82, 88)',
    padding: 0,
    paddingRight: 8,
    display: isDisabled ? 'none' : 'initial',
    '&:hover': {
      color: 'rgb(77, 82, 88)',
    },
    svg: {
      height: 16,
    },
  }),
  container: provided => ({
    ...provided,
    transition: 'border-color ease-in-out .15s, box-shadow ease-in-out .15s',
    fontFamily: '"Open Sans", Helvetica, Arial, sans-serif',
    padding: 0,
    border: '1px solid transparent',
    'border-color': 'rgb(187, 187, 187)',
  }),
  singleValue: (provided, { isDisabled }) => ({
    ...provided,
    minHeight: 20,
    'font-size': 12,
    marginLeft: 0,
    fontWeight: '600',
    color: isDisabled ? 'rgba(54, 54, 54, 0.4)' : 'rgb(54, 54, 54)',
  }),
  menu: provided => ({
    ...provided,
    background: '#fff',
    margin: 0,
    borderRadius: 0,
    paddingTop: 5,
    paddingBottom: 5,
  }),
  control: provided => ({
    ...provided,
    border: 'none',
    transition: 'border-color ease-in-out .15s, box-shadow ease-in-out .15s',
    'box-shadow': '0 2px 3px rgba(3, 3, 3, 0.1)',
    padding: 0,
    minHeight: 'initial',
    'background-color': '#f1f1f1',
    color: '#4d5258',
    'background-image': 'linear-gradient(to bottom, #fafafa 0%, #ededed 100%)',
    'background-repeat': 'repeat-x',
    cursor: 'pointer',
    'white-space': 'nowrap',
    'font-size': 12,
    'border-radius': 1,
    'font-weight': '600',
    '&:hover': {
      'background-color': '#f1f1f1',
      'background-image': 'none',
      'border-color': '#bbbbbb',
      color: '#4d5258',
    },
  }),
  multiValue: (provided, { isDisabled }) => ({
    ...provided,
    background: 'transparent',
    paddigTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    margin: 0,
    '&:nth-last-child(2)': {
      marginRight: 2,
    },
    '&:not(:first-child)': {
      '::before': {
        content: '",\\00a0"',
        'font-size': 12,
        paddingLeft: 0,
        paddingRight: 0,
        fontWeight: '600',
        color: isDisabled ? 'rgba(54, 54, 54, 0.4)' : 'rgb(54, 54, 54)',
      },
    },
  }),
  multiValueRemove: () => ({
    display: 'none',
    padding: 0,
  }),
  multiValueLabel: (provided, { isDisabled }) => ({
    ...provided,
    'font-size': 12,
    padding: 0,
    paddingLeft: 0,
    marginTop: 0,
    marginBottom: 0,
    fontWeight: '600',
    color: isDisabled ? 'rgba(54, 54, 54, 0.4)' : 'rgb(54, 54, 54)',
  }),
  clearIndicator: (provided) => ({
    ...provided,
    padding: 0,
    color: '#4d5258',
    '&:hover': {
      color: '#4d5258',
    },
    svg: {
      height: 16,
    },
  }),
};

export default customStyles;
