name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    if: github.repository == 'data-driven-forms/react-forms'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3-preview
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
